### ISSUE TITLE
你好，请问一下这个项目怎么分包，上传的时候显示主包>4M，请问如何解决

### ISSUE THREAD

**Issue by woshizx** [a1192138141/synthesis_watermelon#1]

**Comment by Degree-21** [comment]
删除img示例图文件夹后重试

**Comment by woshizx** [comment]
> 
> 
> 删除img示例图文件夹后重试

还是太大，
![图片](https://user-images.githubusercontent.com/43931672/106080849-d1342480-6152-11eb-9015-bd0b57aea33c.png)

**Comment by woshizx** [comment]
> 
> 
> 删除img示例图文件夹后重试

还是太大，Error: 系统错误，错误码：80051,source size 4747KB exceed max limit 4MB

**Comment by Degree-21** [comment]
获取最新代码后重试
